export * as ItemService from './ItemService.js'
export * as ResurfaceService from './ResurfaceService.js'
export * as StreakService from './StreakService.js'
export * as AnalyticsService from './AnalyticsService.js'
export * as EngagementService from './EngagementService.js'
export * as ClusterUserIntentService from './ClusterUserIntentService.js'
export * as InterestStateService from './InterestStateService.js'
// v3.1.29 · 共享地形分类（兴趣地图角标 + §3 §3 地形 共用）
export * as TerrainClassifier from './TerrainClassifier.js'
export type { TerrainType, TerrainResult, ClassifyInput } from './TerrainClassifier.js'
export { TERRAIN_LABELS_MAP, TERRAIN_LABELS_PROFILE, TERRAIN_COLORS } from './TerrainClassifier.js'
export * as AIInsightsService from './AIInsightsService.js'
export * as Migration from './Migration.js'
export * as ReleaseReasonPredictor from './ReleaseReasonPredictor.js'
export type { PredictContext } from './ReleaseReasonPredictor.js'
export type { BatchReleaseInput } from './ItemService.js'
export * as EchoIndexService from './EchoIndexService.js'
export type { EchoTier, EchoEntry, EchoIndexInput } from './EchoIndexService.js'
export * as NotificationBudgetService from './NotificationBudgetService.js'
export type { BudgetChannel, BudgetLog } from './NotificationBudgetService.js'
export * as EchoMomentService from './EchoMomentService.js'
export type { EchoMomentThreshold, EchoMomentTriggerResult } from './EchoMomentService.js'
export * as RecallService from './RecallService.js'
export type { RecallTrigger, RecallFiredLog, RecallEvaluation, AbsenceSummary } from './RecallService.js'
export * as MilestoneService from './MilestoneService.js'
export type { MilestoneId, MilestoneFiredLog, MilestoneNotification, MilestoneInput } from './MilestoneService.js'
export type { InsightFeedback } from './AIInsightsService.js'
export type { BookmarkNode } from './ItemService.js'
export type { EngagementLevel, EngagementResult } from './EngagementService.js'
export type { MomentumSignal } from './InterestStateService.js'
export * as ClusterBucketService from './ClusterBucketService.js'
export { UNCLUSTERED_BUCKET } from './ClusterBucketService.js'
export * as IdentityService from './IdentityService.js'
export * as IdentityConstraints from './IdentityConstraints.js'
export type { IdentityConstraint, Violation } from './IdentityConstraints.js'
// v3.1.25 · Mock data factory (testing helper · 也供 preview 用)
export { generateMockData } from '../testing/MockFactory.js'
export type { MockUserSpec } from '../testing/MockFactory.js'
export * as BehavioralChangeService from './BehavioralChangeService.js'
export type { ChangeSignal, ChangeKind } from './BehavioralChangeService.js'
export * as DramaticInsightService from './DramaticInsightService.js'
export type { DramaticInsight, DramaticTemplate } from './DramaticInsightService.js'
export * as PsychGuidanceService from './PsychGuidanceService.js'
export type { PsychGuidance } from './PsychGuidanceService.js'
export * as IntentValidationService from './IntentValidationService.js'
export type {
  IntentReleaseMatrix,
  IntentAnomaly,
  IntentValidationStats,
} from './IntentValidationService.js'
